[tox]
envlist =
    py3
isolated_build = true

[testenv]
package = editable
deps =
    pandas
    pytest
    pytest-cov
    pytest-codeblocks
    pytest-randomly
commands_pre =
    plotly_get_chrome -y
commands =
    pytest {posargs}
