[tox]
envlist =
    py3
isolated_build = True

[testenv]
deps =
    pandas
    pytest
    pytest-cov
    pytest-codeblocks
    pytest-randomly
commands =
    plotly_get_chrome -y
    pytest {posargs}
